package charts.runtime;

import charts.ChartUpdateException;
import org.jfree.chart.JFreeChart;


public interface RuntimesChartProvider {

  /**
   * Returns a chart showing confidence intervals for the runtimes
   * of the queries that were last set via the `update` method.
   *
   * @return a new chart bound to the state of this provider
   */
  JFreeChart getRuntimesChart();

  /**
   * Updates all charts that have been generated by this provider to display
   * the runtimes of the two specified queries, with confidence intervals.
   *
   * @param query1 the first SQL query
   * @param query2 the second SQL query
   * @param numObservations number of observations for each query
   * @param conf the confidence level of the displayed confidence intervals
   * @throws ChartUpdateException for all kinds of errors that prevent
   *     displaying the charts
   */
  void update(String query1, String query2, int numObservations, double conf)
      throws ChartUpdateException;
}
